server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:8085
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: ENTERPRISE-SERVICE
          uri: lb://ENTERPRISE-SERVICE
          predicates:
            - Path=/enterprises/**,/staffs/**,/staffs/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

        - id: GAME-SERVICE
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/games/**

        - id: CATEGORY-SERVICE
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/categories/**


#Etape 4 de notre fichier contenant le guide des étapes à suivre pour la mise en place de notre microservice
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultzone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}